background_b: 255
background_g: 86
background_r: 150
rosdistro: 'hydro

  '
roslaunch:
  uris: {host_meng_lenovo_k4450__35374: 'http://meng-Lenovo-K4450:35374/'}
rosversion: '1.10.11

  '
run_id: b42005fe-80e3-11e4-84eb-3c970eed8c23
